{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-{{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "pdf-preview-fe-global.labels" . | nindent 4 }}
  #### add these annotations to upgrade Helm version with no downtime
  annotations:
    {{- include "pdf-preview-fe-global.annotations" . | nindent 4 }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  #### end of annotations
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
      - secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: svc-{{ $.Values.app.name }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
