apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    svc_role: {{ .Values.app.name }}-monitor
    {{- include "pdf-preview-fe-global.labels" . | nindent 4 }}
    ###add these annotations for helm upgrade
  annotations:
    {{- include "pdf-preview-fe-global.annotations" . | nindent 4 }}
    ### end of annotations
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pdf-preview-fe-global.selectorLabels" . | nindent 4 }}