deployList:
  repeatableSets:
  - deploySet:
      conciergeCheck:
        environment: qa
        artifact:
          name: dxs/pdf-preview-fe-global
          version: 1.0.43
        tenant: HU
      install:
        tool:
          helm:
            path: helm/pdf-preview-fe-global
            values: helm/pdf-preview-fe-global/values-qat-hu.yaml
            releaseName: pdf-preview-fe-global-qat
            uninstallOnFailure: true
      label: qat