deployList:
  repeatableSets:
  - deploySet:
      conciergeCheck:
        environment: sit
        artifact:
          name: dxs/pdf-preview-fe-global
          version: 1.0.43
        tenant: C0
      install:
        tool:
          helm:
            path: helm/pdf-preview-fe-global
            values: helm/pdf-preview-fe-global/values-sit-it.yaml
            releaseName: pdf-preview-fe-global-sit
      label: SIT