deployList:
  repeatableSets:
  - deploySet:
      conciergeCheck:
        environment: dev
        artifact:
          name: dxs/pdf-preview-fe-global
          version: 1.0.43
        tenant: HR
      install:
        tool:
          helm:
            path: helm/pdf-preview-fe-global
            values: helm/pdf-preview-fe-global/values-dev-hr.yaml
            releaseName: pdf-preview-fe-global-dev
            uninstallOnFailure: true
      label: dev