# Default values for emb-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

app:
  name: pdf-preview-fe-global
  namespace: ns-dxs-fe-digitalsignature
  environment: qa
  version: v1.0.3
  tier: fe
  cee_countries_config: false

image:
  repository: artifactory.devops.internal.unicreditgroup.eu/dxs-docker-internal/dxs/pdf-preview-fe-global
  tag: 1.0.43
  # restart pod after every deploy
  forceRestart: true
  pullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70


imagePullSecrets:
  - name: sct-artifactory-registry-creds

ingress:
  enabled: true
  className: "dxs-nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: channel.it.dxs.uat.g4c.unicredit.eu
      paths:
      - /dxs/pdf-preview-fe-global[/]?(.*)
  tls:
    - secretName: sct-tls-ingress

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - pdf-preview-fe-global
      topologyKey: kubernetes.io/hostname

livenessProbe:
  initialDelaySeconds: 30
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP

pdb:
  enable: true

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

monitor:
  enabled: true

service:
  port: 8080
  type: "ClusterIP"
  nodePort: ""
  pathType: Prefix

config:
  requiresAuthentication: false

