# Default values for emb-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

app:
  name: pdf-preview-fe-global
  namespace: ns-dxs-fe-digitalsignature
  sidecarUrl: eu.gcr.io/ucs-sml-lab-001/cloudsql-docker/gce-proxy:1.17
  dbUrl: ucs-sml-lab-001:europe-west4:sql-sml-lab-pgsql001=tcp:5432
  environment: sit
  version: v1.0.3
  tier: fe

image:
  repository: artifactory.devops.internal.unicreditgroup.eu/dxs-docker-internal/dxs/pdf-preview-fe-global
  tag: 1.0.43
  # restart pod after every deploy
  forceRestart: true
  pullPolicy: Always

imagePullSecrets:
  - name: sct-artifactory-registry-creds

ingress:
  enabled: true
  className: "dxs-nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 150m
    memory: 150Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - pdf-preview-fe-global
      topologyKey: kubernetes.io/hostname

livenessProbe:
  initialDelaySeconds: 30
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP

pdb:
  enable: true

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

service:
  port: 8080
  type: "ClusterIP"
  nodePort: ""
  pathType: Prefix
